cargo-features = ["different-binary-name"]

[package]
name = "pigeon-rs"
version = "0.1.3"
authors = ["quambene <contact.quambene@gmail.com>"]
description = "Command line tool for cheap and efficient email automation"
edition = "2018"
homepage = "https://github.com/quambene/pigeon-rs"
repository = "https://github.com/quambene/pigeon-rs"
documentation = "https://github.com/quambene/pigeon-rs"
keywords = ["mail", "email", "automation", "cli"]
categories = ["command-line-utilities", "email"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.40"
rusoto_sesv2 = "0.46.0"
rusoto_core = "0.46.0"
rusoto_credential = "0.46.0"
yaml-rust = "0.4.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_yaml = "0.8.17"
whoami = "1.1.1"
tokio = "1.12.0"
csv = "1.1.6"
clap = "2.33.3"
chrono = "0.4.19"
polars = "0.16"
polars-core = "0.16"
connectorx = { version = "0.2.2-alpha.5", features = ["src_postgres", "dst_arrow2"] }
postgres = "0.19.2"
url = "2.2.2"

[patch.crates-io]
connectorx = { path = "../connector-x/connectorx" }

[[bin]]
name = "pigeon-rs"
filename = "pigeon"
path = "src/main.rs"
