version: '3'
services:
  postgres:
    volumes:
      - ./test_data:/docker-entrypoint-initdb.d
    image: postgres:16-alpine
    restart: "no"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
